version: '3'

services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    environment:
      - HOST=0.0.0.0
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_USER=mohammed
      - DB_PASSWORD=mohammed
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: mohammed
      POSTGRES_USER: mohammed
      POSTGRES_PASSWORD: mohammed
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
